---
title: "SII: Fund ESG Scoring"
author: "Chetan Ramlall"
date: 23 June 2021
output: html_document
theme: bootstrap
DisplayMode: Showcase
---

```{r setup, echo = FALSE, message=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(knitr)
library(plotly)
library(DT)

source("stanlib.pal.R")

options(scipen = 1, digits = 4)

User <- Sys.getenv("USERNAME")

ReportsPath <- paste0("C:/Users/",User,"/Standard Bank/Index Investments - General/Code/Pub/Operations/STANLIB Ops/data/")

```

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("logo.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```

# ESG Scoring {.tabset .tabset-fade .tabset-pills}


## Summary {.tabset .tabset-fade .tabset-pills}

```{r initial, echo = FALSE, message=FALSE}
# Read the SII Fund List
AllFundList <- read_csv(paste0(ReportsPath,"SII Full Fund List.csv"), col_types = cols())

# Filter for Active
FundList <- AllFundList %>% filter(Active == TRUE) %>% select(-Note, -Active)

# Read Today's Data
Today <- format(Sys.Date()-1, "%Y%m%d")

CRIMSFileName <- paste0(Today,"QISPositionRecon.csv")
CRIMSFilePath <- "//slbappprd217v/QIS/SODRecon/"

CRIMSFile <- read_csv(paste0(CRIMSFilePath, CRIMSFileName), col_types = cols(Datadate = col_date("%d/%m/%Y"))) 

CRIMSFile <- CRIMSFile %>% 
  rename(date = Datadate) %>% 
  rename(ACCT_CD = Acct_CD)

```

**Note: For the purposes of the analysis, Bloomberg ESG Scoring data has been used.**

```{r, echo = FALSE, message=FALSE}

ValidSecTypes <- c("LU","NVS","OS","PUT","REIT")

FilteredCRIMSFile <- CRIMSFile %>%
  filter(ACCT_CD %in% FundList$`HiPort Code`) %>% 
  filter(Category == "Investment") %>% 
  filter(SecTypCd %in% ValidSecTypes) %>% 
  select(date, ACCT_CD, Ticker, SecurityName, SecTypCd, PortfolioWeight = POS_PCT, ModelWeight = MDL_PCT) 
  
ESGScoresBBG <- read_csv("BBG_ESG_Scoring2020.csv") %>% 
  na.omit() %>%   #omit all stocks with no scores
  mutate(Ticker = substr(Ticker,1,3))   #account for BBG naming, removes "SJ Equity".         

CombinedData <- FilteredCRIMSFile %>% 
  left_join(ESGScoresBBG, by = c("Ticker")) %>% 
  na.omit() %>% 
  group_by(ACCT_CD) %>% 
  mutate(ScaledPortfolioWeight = `PortfolioWeight`/sum(`PortfolioWeight`)) %>%
  mutate(ScaledModelWeight = `ModelWeight`/sum(`ModelWeight`)) %>% 
  summarise(`ESG Score` = crossprod(ScaledPortfolioWeight,ESG_Score),
            `E Score` = crossprod(ScaledPortfolioWeight,E_Score),
            `S Score` = crossprod(ScaledPortfolioWeight,S_Score),
            `G Score` = crossprod(ScaledPortfolioWeight,G_Score)) %>% 
  na.omit() %>% 
  ungroup()

# Convert data into long form for plotting.
LongData <- CombinedData %>% 
  gather(Key, Value, `ESG Score`:`G Score`)


```

```{r, echo = FALSE, message=FALSE}

p <- LongData %>%
  ggplot(aes(ACCT_CD, Value, fill = Key)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  #geom_hline(yintercept = 0.05, color = "red") +
  facet_wrap(~Key) +
  #scale_y_continuous(labels = scales::percent) +
  labs(title = "ESG Scoring Profile (%)", y = "", x = "") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))+
  scale_color_manual(values = stanlib.pal()) 

ggplotly(p)

```

## Data {.tabset .tabset-fade .tabset-pills}


```{r, echo = FALSE}
CombinedData %>% 
  DT::datatable( class = 'cell-border stripe',
                 filter = 'top',
                 extensions = 'Buttons',
                 options = list(pageLength = 15,
                                autoWidth = TRUE,
                                dom = 'Blfrtip',
                                buttons = c('copy','excel','csv'),
                                columnDefs = list(list(className = 'dt-center', targets = "_all"))))
                               
```

